import { getHttpClient } from '@/shared/api/client';
import {
  decodeGameResponse,
  decodeMoveResponse,
  decodeSubmitSolutionResponse,
  encodeDifficulty,
  encodeGameMode,
} from '@/shared/api/enumCodec';
import type {
  CreateGameRequest,
  GameMoveRequest,
  GameResponse,
  HintResponse,
  MoveResponse,
  SubmitSolutionRequest,
  SubmitSolutionResponse,
} from '@/shared/api/types';

const base = '/games';

// The backend serializes enums as integers (no JsonStringEnumConverter on the
// API), so we marshal between our string-typed enums and the wire integers at
// this boundary. Inside the app everything stays as readable strings.
interface CreateGameWireRequest {
  mode: number;
  difficulty: number;
}

export const gamesApi = {
  create: async (req: CreateGameRequest, signal?: AbortSignal): Promise<GameResponse> => {
    const wire: CreateGameWireRequest = {
      mode: encodeGameMode(req.mode),
      difficulty: encodeDifficulty(req.difficulty),
    };
    const raw = await getHttpClient().post<unknown, CreateGameWireRequest>(base, wire, {
      anonymous: true,
      signal,
    });
    return decodeGameResponse(raw);
  },

  // Idempotent get-or-create for today's daily game. Backend collapses
  // duplicate calls for the same (userId, date) tuple.
  createDaily: async (signal?: AbortSignal): Promise<GameResponse> => {
    const raw = await getHttpClient().post<unknown>(`${base}/daily`, undefined, { signal });
    return decodeGameResponse(raw);
  },

  get: async (gameId: string, signal?: AbortSignal): Promise<GameResponse> => {
    const raw = await getHttpClient().get<unknown>(`${base}/${gameId}`, { anonymous: true, signal });
    return decodeGameResponse(raw);
  },

  // Each move carries its own Idempotency-Key (auto-generated by the http
  // client). The move queue ensures we never have two of these in flight
  // concurrently per game.
  applyMove: async (
    gameId: string,
    req: GameMoveRequest,
    signal?: AbortSignal,
  ): Promise<MoveResponse> => {
    const raw = await getHttpClient().post<unknown, GameMoveRequest>(
      `${base}/${gameId}/moves`,
      req,
      { anonymous: true, signal },
    );
    return decodeMoveResponse(raw);
  },

  submitSolution: async (
    gameId: string,
    req: SubmitSolutionRequest,
    signal?: AbortSignal,
  ): Promise<SubmitSolutionResponse> => {
    const raw = await getHttpClient().post<unknown, SubmitSolutionRequest>(
      `${base}/${gameId}/solution`,
      req,
      { anonymous: true, signal },
    );
    return decodeSubmitSolutionResponse(raw);
  },

  hint: (gameId: string, signal?: AbortSignal) =>
    getHttpClient().post<HintResponse>(`${base}/${gameId}/hint`, undefined, { anonymous: true, signal }),

  abandon: (gameId: string, signal?: AbortSignal) =>
    getHttpClient().post<void>(`${base}/${gameId}/abandon`, undefined, { anonymous: true, signal }),
};
